title: Sadu Ashritha | Developer Portfolio
logo: /assets/img/ashritha-logo.png  # Replace with your custom logo path if available
description: A minimal yet creative portfolio of Sadu Ashritha - Developer | ML Enthusiast | Innovator
show_downloads: false
google_analytics:  # Add your tracking ID here if needed
theme: jekyll-theme-minimal
